version: '3'
services:
  mongodb:
  image: mongo
  ports: 
    - 27017: 27017
    environment:
    - MONGO_INITDB_ROOT_USERNAME=admin
    - MONGO_INITDB_ROOT_password=4yrv394
  mongo-express:
    image:mongo-express
    ports:
      - 8080: 8081
      environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME = admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD = adhew732lett
      - ME_CONFIG_MONGODB_SERVER = mongodb
